### ISSUE TITLE
能将播放模块跟解析模块分开吗？

### ISSUE THREAD

**Issue by yovenny** [TedaLIEz/ParsingPlayer#10]
就很多时候我只想得到播放的地址
```java
    private void setConcatContent(String content) {
        LogUtil.i(TAG, "set temp file content: \n" + content);
        mPlayer.setConcatVideoPath(SystemClock.currentThreadTimeMillis() + "",
                content, new LoadingCallback<String>() {
                    @Override
                    public void onSuccess(final String result) {
                       // use post here to run in main thread
                        setVideoURI(Uri.parse(result));
                    }

                    @Override
                    public void onFailed(Exception e) {
                        Log.wtf(TAG, e);
                    }
                });
    }
```
在这里交给自己的播放器，还是我理解错了。

**Comment by CoXier** [comment]
Please see [VideoInfo](https://github.com/TedaLIEz/ParsingPlayer/blob/master/parsingplayer/src/main/java/com/hustunique/parsingplayer/parser/VideoParser.java).

**Comment by yovenny** [comment]
thanks~~

**Comment by yovenny** [comment]
if use for reference you-get ? it has more parse...

**Comment by yovenny** [comment]
i think if it has tow compile ‘videoplayer’ and compile ‘videopaser’ will look good，cause it has ijkplayer already in my project？

**Comment by CoXier** [comment]
You can import the `parse' part manualy

**Comment by yovenny** [comment]
哦

**Comment by yovenny** [comment]
```java
 ffconcat version 1.0
 file http://k.youku.com/player/getFlvPath/sid/048833536263412228ae1_00/st/flv/fileid
duration 214.0
```
1.ijkplayer.mediaPlayer.setDataSource(uri) uri为播放信息文件，是它固有的调用方式吗？
2.我用了别人的库没有实现这个方法，有其他替代的实现吗？，但优酷有一个视频好几个播放源的，
可能还要乖乖的实现这个吗？

**Comment by TedaLIEz** [comment]
`uri` points out the video source, you may check [ffconcat](https://trac.ffmpeg.org/wiki/Concatenate) for details.
