### ISSUE TITLE
parse youku's url error

### ISSUE THREAD

**Issue by scrat000** [TedaLIEz/ParsingPlayer#12]
youku‘s url has 3 types

http://v.youku.com/v_show/id_XMjU1MTY3MTM2MA==.html

iframe
http://player.youku.com/embed/XMjU1MTY5MzA5Ng==

flash&embed 
http://player.youku.com/player.php/Type/Folder/Fid//Ob//sid/XMjU1MTY5MzA5Ng==/v.swf

If it can support parsing the url like   http://player.youku.com/embed/XMjU1MTY5MzA5Ng== will be better.

**Comment by CoXier** [comment]
Thanks for your suggestion
